### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by hungnv24** [Azakur4/autocomplete-php#8] opened 2015-05-12 08:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-php](https://github.com/Azakur4/autocomplete-php) package, v0.3.3

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fhung.v.nguyen%2FDesktop%2FRageServer%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.198.0%22%2C%22shellLoadTime%22%3A507%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fhung.v.nguyen%2FDesktop%2FRageServer%22%5D%7D:1

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Socket.<anonymous> (/Users/hung.v.nguyen/.atom/packages/autocomplete-php/lib/provider.coffee:39:31)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  4x -1:16.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:43.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:37.4.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:36.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:29.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -0:23.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
 34x -0:17.1.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12 core:save (atom-text-editor.editor.is-focused)
     -0:09.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "flash_sp",
      "flash",
      "image_sp",
      "application/cache"
    ],
    "disabledPackages": []
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.3
autocomplete-plus, v2.14.1
color-picker, v1.7.0

# Dev
No dev packages
```

**Comment by Azakur4** [comment] 2015-05-12 14:54
can u post a portion of code that throw this error pls.

**Comment by howanghk** [comment] 2015-05-13 10:10
I am having the same issue but I cannot show you the code that I work on.
However I found a file from the Internet that also trigger this issue. http://cl.ly/axSG

Just open the file in Atom with autocomplete-plus and autocomplete-php installed, and start typing in the editor.

**Comment by Azakur4** [comment] 2015-05-13 12:33
thanks, that file helps a lot i was able to reproduce the issue here i will review when this erro happen and try to release a new version soon.

**Comment by Azakur4** [comment] 2015-05-13 13:29
New version release pls test to see this issue is fixed

**Comment by howanghk** [comment] 2015-05-15 10:07
I was able to reproduce the problem with Atom 0.198 and autocomplete-php upgraded from 0.3.3 to 0.3.6 (without restarting Atom). But after upgrading to Atom 0.199 it seems to be working fine for now.

**Comment by Azakur4** [comment] 2015-05-15 13:15
Nice, do you think that we can close this issue or u prefer let it open to wait more feedback?

**Comment by howanghk** [comment] 2015-05-18 04:43
@Azakur4 I was not able to reproduce this issue in the past few days, I would consider this is fixed and can be closed. (and you may re-open it if anyone encounter the issue again) 
Thanks for all the great work! :+1:

**Comment by Azakur4** [comment] 2015-05-18 14:26
thanks for the feedback. closed

**Closed by Azakur4** 2015-05-18 14:26 UTC
Labels: bug
