### ISSUE TITLE
autocomplete for php ide_helper files

### ISSUE THREAD

**Issue by funsterisdafunniest** [Azakur4/autocomplete-php#7] opened 2015-05-11 08:59 UTC
hi, i was wondering if it's possible to read files generated by this project <a href="https://github.com/barryvdh/laravel-ide-helper">barryvh laravel ide helper</a>. The project would generate a "_ide_helper.php" file and the ide (either phpstorm, or sublime) would be able to read that file and provide autocomplete for the libraries that exist inside the laravel project.

is this possible to do in this package?

**Comment by Azakur4** [comment] 2015-05-12 06:12
Hi, i will review that. i'm studying to see what is the best way and if i will do the autocompletion for php custom objects.

This part is a little hard and have some ways to make it but i can't think only in one framework i have to make something more general to support other frameworks too.

**Comment by funsterisdafunniest** [comment] 2015-05-12 06:56
yeah, i do know the complicated process for this feature to be added. how about searching for the class under vendor first? (the one that created by composer) it might prove to be easier for a start rather than implementing full project indexing for autocompleting all custom classes

**Comment by Azakur4** [comment] 2015-05-12 15:12
Yeah i know but im thinking what can be better atom is a web app. i don't wanna get overcharge with extra process out, like running php to scan all custom classes in a project. In my first tentative to make this package, i only focus in one file, the file u are using or writing in that moment to help with auto completions.

The problem actually not is only scanning all files the problem is that this can be recursive cuz if u are working in one file and after u modify other u always have to be scanning all files to get all the suggestions any time u write in that process im worried about affect the performance of the editor.

Until now im working more in validate all the errors parsing php code but i go give a time to see more ways to get a better auto complete with php projects.

I test the phpintel from sublime to see how this work and see is this get custom objects autocomplete maybe we can integrate that here.

**Comment by funsterisdafunniest** [comment] 2015-05-12 15:19
I see what you mean, it might produce extensive performance impact to just scan everything on each autocomplete request. Thanks for looking into it!

**Comment by Azakur4** [comment] 2015-05-12 15:23
Yes no problem i wait for give u good news in near future :P if i found a good way to do that :) i will close this for now but if i found a good way i will reopen to talk about this.

**Closed by Azakur4** 2015-05-12 15:23 UTC
